name: ci

on:
  push:
    branches:
      - develop
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: ${{ vars.REGISTRY_HOST }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
              AUTH_API_URL=${{ vars.AUTH_API_HOST }}
              ADMIN_API_URL=${{ vars.ADMIN_API_HOST }}
              BASE_URL=${{ vars.BASE_URL }}
          tags: |
            ${{ vars.DOCKER_REPO }}/rfid-admin-front:latest
            ${{ vars.DOCKER_REPO }}/rfid-admin-front:${{ github.sha }}
      - 
        name: kube update
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: kubectl set image deployments --namespace=rfid-dev --selector="app=admin-front" admin-front=registry.rolandsobczak.com/rfidio/rfid-admin-front${{ github.sha }}
